; ============================================
; FICHIER DE CONFIGURATION SIP (chan_sip)
; Projet OP-1 - Hotel de la Plage
; ============================================
; Ce fichier definit :
;   - Les parametres generaux SIP
;   - Les comptes SIP de chaque telephone IP
; ============================================

[general]
; --- Parametres reseau ---
bindport=5060                    ; Port d'ecoute SIP
bindaddr=0.0.0.0                 ; Ecoute sur toutes les interfaces
context=hotel                    ; Contexte dialplan par defaut

; --- Codecs autorises ---
disallow=all                     ; Desactive tous les codecs
allow=ulaw                       ; Autorise G.711 ulaw
allow=alaw                       ; Autorise G.711 alaw

; --- Securite ---
alwaysauthreject=yes             ; Rejette toujours avec auth (anti-scan)
allowguest=no                    ; Pas d'appels anonymes

; --- NAT ---
nat=force_rport,comedia          ; Gestion NAT

; ============================================
; RECEPTION - Extension 1099
; Le client compose le 1099 pour joindre
; la reception de l'hotel
; ============================================
[1099]
type=friend                      ; Peut appeler et recevoir des appels
username=1099
secret=reception123              ; Mot de passe du compte SIP reception
host=dynamic                     ; IP dynamique (enregistrement SIP)
context=hotel                    ; Contexte dialplan
callerid="Reception" <1099>      ; Nom affiche sur les telephones
qualify=yes                      ; Verifie que le telephone est joignable

; ============================================
; CHAMBRE 1001 - 1er etage
; IP fixe : 192.168.30.101 port 5065
; ============================================
[1001]
type=friend                      ; Peut appeler et recevoir des appels
username=1001
secret=chambre1001               ; Mot de passe du compte SIP chambre 1001
host=dynamic	                 ; IP dynamique de la chambre 1001
port=5065                        ; Port SIP de la chambre 1001
context=hotel                    ; Contexte dialplan
callerid="Chambre 1001" <1001>   ; Nom affiche lors d'un appel sortant
qualify=yes                      ; Verifie que le telephone est joignable

; ============================================
; CHAMBRE 1002 - 1er etage
; ============================================
[1002]
type=friend
username=1002
secret=chambre1002
host=dynamic
context=hotel
callerid="Chambre 1002" <1002>
qualify=yes

; ============================================
; CHAMBRE 1003 - 1er etage
; ============================================
[1003]
type=friend
username=1003
secret=chambre1003
host=dynamic
context=hotel
callerid="Chambre 1003" <1003>
qualify=yes
